In [1]:
import numpy as np

In [2]:
def hat(X):
    
    T=np.mat(X.T)
    H = X.dot(np.linalg.inv(T.dot(X))).dot(T)
    
    return H

In [13]:
X = np.mat([
    [1,-1,-2,-3,1],
    [1,-3,-2,-1,1],
    [1,-1,-1,-4,1],
    [1,0,-5,-1,5],
    [1,-2,-2,-2,1],
])
print(X)
print(X.T.dot(X))
print(np.linalg.inv(X.T.dot(X)))
hat(X)

[[ 1 -1 -2 -3  1]
 [ 1 -3 -2 -1  1]
 [ 1 -1 -1 -4  1]
 [ 1  0 -5 -1  5]
 [ 1 -2 -2 -2  1]]
[[  5  -7 -12 -11   9]
 [ -7  15  13  14  -7]
 [-12  13  38  21 -32]
 [-11  14  21  31 -15]
 [  9  -7 -32 -15  29]]
[[-3.51339986e+15 -5.85566643e+14 -5.85566643e+14 -5.85566643e+14
  -2.42713492e+00]
 [-5.85566643e+14 -9.75944404e+13 -9.75944404e+13 -9.75944404e+13
  -1.04514749e+00]
 [-5.85566643e+14 -9.75944404e+13 -9.75944404e+13 -9.75944404e+13
   1.28818585e+00]
 [-5.85566643e+14 -9.75944404e+13 -9.75944404e+13 -9.75944404e+13
  -4.20147487e-01]
 [-2.18947453e+00 -1.00553742e+00  1.32779591e+00 -3.80537421e-01
   1.73958333e+00]]


matrix([[ 1.046875  ,  0.140625  ,  0.36458333, -0.28645833,  0.59375   ],
        [ 0.109375  ,  1.328125  ,  0.30208333,  0.08854167,  0.71875   ],
        [ 0.30208333,  0.55208333,  1.38541667, -0.07291667,  0.42708333],
        [ 0.29166667,  0.47916667,  0.33333333,  1.07291667,  0.38541667],
        [ 0.84375   ,  1.09375   ,  0.61458333,  0.07291667,  0.96875   ]])

In [4]:
X2 = X*2
hat(X2)

matrix([[ 1.046875  ,  0.140625  ,  0.36458333, -0.28645833,  0.59375   ],
        [ 0.109375  ,  1.328125  ,  0.30208333,  0.08854167,  0.71875   ],
        [ 0.30208333,  0.55208333,  1.38541667, -0.07291667,  0.42708333],
        [ 0.29166667,  0.47916667,  0.33333333,  1.07291667,  0.38541667],
        [ 0.84375   ,  1.09375   ,  0.61458333,  0.07291667,  0.96875   ]])

In [5]:
X3 = np.mat([
    [1,-1*2,-2*3,-3*4,1*5],
    [1,-3*2,-2*3,-1*4,1*5],
    [1,-1*2,-1*3,-4*4,1*5],
    [1,0*2,-5*3,-1*4,5*5],
    [1,-2*2,-2*3,-2*4,1*5],
])
hat(X3)

matrix([[-2.21875   , -4.46875   , -3.10416667, -2.27083333, -3.34375   ],
        [-7.78125   , -7.03125   , -7.26041667, -8.55208333, -7.40625   ],
        [-4.44791667, -4.19791667, -3.73958333, -3.69791667, -4.32291667],
        [-3.42708333, -3.67708333, -3.66666667, -1.58333333, -3.55208333],
        [-7.65625   , -7.40625   , -7.63541667, -9.17708333, -7.53125   ]])

In [6]:
X4 = np.mat([
    [1,-1,-2,-3,1],
    [1/2,-3/2,-2/2,-1/2,1/2],
    [1/3,-1/3,-1/3,-4/3,1/3],
    [1/4,0/4,-5/4,-1/4,5/4],
    [1/5,-2/5,-2/5,-2/5,1/5],
])
hat(X4)

matrix([[6.625     , 2.13392857, 1.99801587, 1.30505952, 1.08928571],
        [1.38392857, 1.35267857, 0.52281746, 0.30431548, 0.40892857],
        [0.99801587, 0.52281746, 1.34589947, 0.21378968, 0.20436508],
        [0.61755952, 0.21056548, 0.23462302, 1.11421131, 0.10386905],
        [1.30178571, 0.87767857, 0.37936508, 0.33199405, 0.30571429]])

In [7]:
X5 = np.mat([
    [-5,-1,-2,-3,1],
    [-5,-3,-2,-1,1],
    [-5,-1,-1,-4,1],
    [-5,0,-5,-1,5],
    [-5,-2,-2,-2,1],
])
hat(X5)

matrix([[-2.28125   , -5.28125   , -3.82291667,  0.01041667, -3.78125   ],
        [-2.03125   , -1.53125   , -2.82291667,  1.26041667, -1.78125   ],
        [-3.94791667, -5.69791667, -3.73958333, -0.69791667, -4.82291667],
        [-3.23958333, -4.73958333, -3.94791667,  0.63541667, -3.98958333],
        [-2.53125   , -3.78125   , -3.32291667, -0.86458333, -3.15625   ]])

In [8]:
X = np.mat([
    [2,2,1,1,0],
    [3,2,1,2,1],
    [4,1/2,1/3,3,1],
    [5,1/2,1/3,4,1],
    [1,1/2,1/3,5,1],
])

hat(X)

matrix([[ 1.00000000e+00,  1.41664458e-13, -6.88338275e-14,
          9.76996262e-14,  2.04281037e-14],
        [ 4.21884749e-14,  1.00000000e+00,  1.33892897e-13,
         -8.90398866e-14,  6.66133815e-16],
        [-5.24025268e-14,  1.79856130e-13,  1.00000000e+00,
          2.40696352e-13, -7.10542736e-15],
        [ 2.26485497e-14, -1.33670852e-13,  2.25486296e-13,
          1.00000000e+00,  6.66133815e-16],
        [ 3.41948692e-14,  4.39648318e-14, -7.66053887e-15,
          1.65423231e-14,  1.00000000e+00]])

In [9]:
X = np.mat([
    [2,4,3,4,0],
    [3,4,3,8,5],
    [4,1,1,12,5],
    [5,1,1,16,5],
    [1,1,1,20,5],
])

hat(X)

matrix([[ 1.00000000e+00,  9.54791801e-15, -4.92939023e-14,
          2.33146835e-14, -1.33226763e-14],
        [-9.43689571e-16,  1.00000000e+00,  5.53723734e-14,
         -4.81004125e-14,  5.63438185e-15],
        [ 7.83817455e-14,  1.86378690e-13,  1.00000000e+00,
          1.60177427e-13,  2.53963517e-14],
        [ 1.39888101e-13,  6.09234885e-14,  1.52849955e-13,
          1.00000000e+00,  4.18276525e-14],
        [-2.77555756e-16,  4.85722573e-15, -8.29891711e-15,
          6.96664948e-15,  1.00000000e+00]])

In [10]:
X = np.mat([
    [1,4,3,4,0],
    [3,4,3,8,5],
    [4,2,1,1,5],
    [5,1,100,16,5],
    [1,1,1,20,5],
])

T = X.T
print(np.linalg.inv(T.dot(X)))
hat(X)

[[ 2.86069852 -0.84206053 -0.10341797  0.37528845 -1.82408451]
 [-0.84206053  0.29539029  0.03100704 -0.11080997  0.5157187 ]
 [-0.10341797  0.03100704  0.00390458 -0.01389939  0.06559342]
 [ 0.37528845 -0.11080997 -0.01389939  0.05424596 -0.24869512]
 [-1.82408451  0.5157187   0.06559342 -0.24869512  1.20456601]]


matrix([[ 1.00000000e+00, -1.77635684e-14, -6.66133815e-15,
         -1.42108547e-14, -3.99680289e-15],
        [-8.43769499e-15,  1.00000000e+00, -1.44328993e-14,
         -2.88657986e-15, -8.21565038e-15],
        [ 1.88737914e-15, -1.08801856e-14,  1.00000000e+00,
         -1.99840144e-15, -1.11022302e-15],
        [-1.20736754e-15, -7.53563878e-15, -8.59035065e-15,
          1.00000000e+00, -6.39766018e-15],
        [ 2.60902411e-15, -1.11022302e-15,  5.55111512e-15,
          3.77475828e-15,  1.00000000e+00]])